[package]
name = "KIT-ILIAS-downloader"
version = "0.2.14"
authors = ["FliegendeWurst <2012gdwu@web.de>"]
license = "GPL-2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.0", default-features = false, features = ["cookies", "gzip", "json", "rustls-tls", "stream"] }
tokio = { version = "1.0.2", features = ["full"] }
tokio-util = { version = "0.6.1", features = ["io"] }
serde_json = "1.0.51"
scraper = "0.12.0"
url = "2.1.1"
futures = "0.3.8"
futures-util = "0.3.8"
futures-channel = "0.3.8"
regex = "1.3.7"
lazy_static = "1.4.0"
parking_lot = "0.11.0"
structopt = "0.3.13"
rpassword = "5.0.0"
rprompt = "1.0.5"
ignore = "0.4.14"
anyhow = "1.0.28"
